apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-jrkyqnwi
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-jrkyqnwi:082f7097fe715a65d89a5646b20a3e51fb83ae66@sha256:3cfa94e4a62376f2671cc934841f97f9046da29a9da4aac9c0bc5dcbb6c259dd
          name: container-image
